#! /bin/bash
set -e
shopt -s nullglob

normalize-mp3 ()
{
	mp3gain -c -q -r "$1"
}

normalize-vorbis ()
{
	printf "$1\n"
	vorbisgain --fast --quiet --skip "$1"
}


normalize-all ()
{
	local file current=0
	for file in "$@" ; do
		printf "[1;1m%02i/%02i[1;33m " "$((++current))" "$#"
		case ${file} in
			*.[oO][gG][aAgG]) printf "[ogg][0;0m " ; normalize-vorbis "${file}" ;;
			*.[mM][pP]3     ) printf "[mp3][0;0m " ; normalize-mp3    "${file}" ;;
			*               ) printf "[   ][0;0m ${file}\n" ;;
		esac
	done
}

[[ $# -eq 0 ]] && set -- *.[mM][pP]3 *.[oO][gG][gGaA]
normalize-all "$@" \
	| grep -vE '^(No changes to|Applying mp3 gain change of|\.\.\.but tag needs update)'

